services:
  frontend:
    build: ./frontend/
    command: npm run dev
    env_file:
      - path: './frontend/.env'
    ports:
      - "5173:5173"
    depends_on:
      - backend
# alembic revision --autogenerate -m "create account table" 
  backend:
    build: ./backend/

    env_file:
      - path: './backend/.env'
    ports:
      - "8000:8000"

    depends_on:
      - db
      - migrate
      - insert_data

  migrate:
        image: forest-fire-gis-app-backend
        command: alembic upgrade head 
        depends_on:
          - db

  insert_data:
        image: forest-fire-gis-app-backend
        command: python data.py
        depends_on:
          - db

  db:
    image: postgis/postgis:16-3.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
    ports:
      - "5436:5432"
  
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=emberwatch

volumes:
  postgres_data: