services:
  frontend:
    build: ./frontend/
    command: npm run dev
    env_file:
      - path: './frontend/.env'
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build: ./backend/
    command: uvicorn main:app --host=0.0.0.0 
    env_file:
      - path: './backend/.env'
    ports:
      - "8000:8000"

    depends_on:
      - db

  db:
    image: postgis/postgis:16-3.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
    ports:
      - "5436:5432"
  
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=emberwatch

volumes:
  postgres_data: